import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/Components/Sidebar/Sidebar'
import { getServerSession } from 'next-auth'
import { options } from './api/auth/[...nextauth]/options'
import AuthProvider from '@/Components/authprovider'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DevBlogger',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  var name = '';
  var img = '';
  var username = ''
  const session = await getServerSession(options);
  if (session) {
    const id = session.user.id;
    const obj = await axios.post('http://localhost:4452/api/user/getUser',{
      id:id
    })
    name = obj.data.name
    username = obj.data.username
    
    img = session.user.pfp;
  } else {
    name = "Please Sign in"
  }

  const getContent = async (children) => {
    
    if (['Register', 'landing'].includes(children.props.childProp.segment)) return (<html lang="en">
      <div>
        <div className="App">
          <div className="AppGlassNon">
            <AuthProvider>
              {children}
            </AuthProvider>
          </div>
        </div>
      </div>
    </html>)


    return (
      <html lang="en">
        <div>
          <div className="App">
            <div className="AppGlass">
              <Sidebar name={name} img={img} username={username} />
              <AuthProvider>
                {children}
              </AuthProvider>
            </div>
          </div>

        </div>
      </html>
    )
  }

  return (getContent(children))

}
